In [4]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [5]:
data= pd.read_csv('Data.csv')

In [6]:
data.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [23]:
x=data.iloc[:,:-1].values
y=data.iloc[:,-1].values


In [24]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [25]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [26]:
data.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [27]:
data

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [39]:
from sklearn.impute import SimpleImputer
si=SimpleImputer(missing_values=np.nan,strategy='mean')
data['Salary']=si.fit(x[:,1:3])
x[:,1:3]=si.transform(x[:,1:3])

# OR
# data['Salary']=data['Salary'].fillna(data['Salary'].mean())

In [41]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [42]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [48]:
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])], remainder='passthrough')

In [50]:
x=np.array(ct.fit_transform(x))

In [51]:
x

array([[0.0, 1.0, 0.0, 0.0, 44.0, 72000.0],
       [1.0, 0.0, 0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 1.0, 0.0, 30.0, 54000.0],
       [1.0, 0.0, 0.0, 1.0, 38.0, 61000.0],
       [1.0, 0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [0.0, 1.0, 0.0, 0.0, 35.0, 58000.0],
       [1.0, 0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [0.0, 1.0, 0.0, 0.0, 48.0, 79000.0],
       [1.0, 0.0, 1.0, 0.0, 50.0, 83000.0],
       [0.0, 1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [55]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

In [58]:
y


array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [64]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=.2,random_state=0)

In [65]:
xtrain

array([[1.0, 0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [0.0, 1.0, 0.0, 0.0, 37.0, 67000.0],
       [1.0, 0.0, 0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [0.0, 1.0, 0.0, 0.0, 48.0, 79000.0],
       [1.0, 0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 1.0, 0.0, 0.0, 35.0, 58000.0]], dtype=object)

In [66]:
xtest

array([[1.0, 0.0, 1.0, 0.0, 30.0, 54000.0],
       [1.0, 0.0, 1.0, 0.0, 50.0, 83000.0]], dtype=object)

In [67]:
ytrain

array([1, 1, 1, 0, 1, 0, 0, 1])

In [68]:
ytest

array([0, 0])

In [69]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()

In [72]:
xtrain[:,3:] =ss.fit_transform(xtrain[:,3:])

In [73]:
xtest[:,3:]=ss.transform(xtest[:,3:])

In [74]:
xtrain

array([[1.0, 0.0, 1.0, -0.7745966692414834, 0.2630675731713538,
        0.1238147854838185],
       [0.0, 1.0, 0.0, -0.7745966692414834, -0.25350147960148617,
        0.4617563176278856],
       [1.0, 0.0, 0.0, 1.2909944487358056, -1.9753983221776195,
        -1.5309334063940294],
       [1.0, 0.0, 0.0, 1.2909944487358056, 0.05261351463427101,
        -1.1114197802841526],
       [0.0, 1.0, 0.0, -0.7745966692414834, 1.6405850472322605,
        1.7202971959575162],
       [1.0, 0.0, 0.0, 1.2909944487358056, -0.08131179534387283,
        -0.16751412153692966],
       [0.0, 1.0, 0.0, -0.7745966692414834, 0.9518263102018072,
        0.9861483502652316],
       [0.0, 1.0, 0.0, -0.7745966692414834, -0.5978808481167128,
        -0.48214934111933727]], dtype=object)

In [75]:
xtest

array([[1.0, 0.0, 1.0, -0.7745966692414834, -1.4588292694047795,
        -0.9016629672292141],
       [1.0, 0.0, 1.0, -0.7745966692414834, 1.984964415747487,
        2.139810822067393]], dtype=object)