In [2]:

import matplotlib.pyplot as plt 
import numpy as np 
import pandas as pd 

# %%
data = pd.read_csv('Wine.csv')
x = data.iloc[:,:-1].values
y = data.iloc[:,-1].values

# %%
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=.2)

# %%
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
xtrain = sc.fit_transform(xtrain)
xtest = sc.transform(xtest)

from sklearn.decomposition import KernelPCA 
kpca =KernelPCA(n_components=2)
xtrain = kpca.fit_transform(xtrain,ytrain)
xtest = kpca.transform(xtest)

# %%
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(xtrain,ytrain)
res = lr.predict(xtest)
from sklearn.metrics import accuracy_score,confusion_matrix
print(confusion_matrix(res,ytest))
print(accuracy_score(res,ytest))

# %%





[[11  0  0]
 [ 0 12  0]
 [ 0  0 13]]
1.0
