In [14]:
import matplotlib.pyplot as plt 
import numpy as np 
import pandas as pd 

In [15]:
data = pd.read_csv('Wine.csv')
x = data.iloc[:,:-1].values
y = data.iloc[:,-1].values

In [16]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=.2)

In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
xtrain = sc.fit_transform(xtrain)
xtest = sc.transform(xtest)

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis 
lda =LinearDiscriminantAnalysis(n_components=2)
xtrain = lda.fit_transform(xtrain,ytrain)
xtest = lda.transform(xtest)

In [18]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(xtrain,ytrain)
res = lr.predict(xtest)
from sklearn.metrics import accuracy_score,confusion_matrix
print(confusion_matrix(res,ytest))
print(accuracy_score(res,ytest))

[[11  0  0]
 [ 0 18  0]
 [ 0  0  7]]
1.0
